### ISSUE TITLE
AXI DMA interrupts incorrectly generated in pl.dtsi

### ISSUE THREAD

**Issue by vgokhale** [Xilinx/device-tree-xlnx#3]
The pl.dtsi incorrectly generates the AXI DMA's interrupts if there are multiple AXI DMAs. Here's a generated pl.dtsi file with 4 AXI DMAs. Notice how the interrupts in the AXI DMA parent node are DIFFERENT from the interrupts in the channel sub-node (can you call it that?)

    axi_dma_0: axi-dma@40400000 {
			compatible = "xlnx,axi-dma";
			interrupt-parent = <&ps7_scugic_0>;
			interrupts = <0 29 4>, <0 30 4>;
			reg = <0x40400000 0x10000>;
			dma-channel@40400000 {
				compatible = "xlnx,axi-dma-mm2s-channel";
				interrupts = <0 36 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x0>;
			} ;
			dma-channel@40400030 {
				compatible = "xlnx,axi-dma-s2mm-channel";
				interrupts = <0 35 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x0>;
			} ;
		} ;
		axi_dma_1: axi-dma@40440000 {
			compatible = "xlnx,axi-dma";
			interrupt-parent = <&ps7_scugic_0>;
			interrupts = <0 31 4>, <0 32 4>;
			reg = <0x40440000 0x10000>;
			dma-channel@40440000 {
				compatible = "xlnx,axi-dma-mm2s-channel";
				interrupts = <0 34 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x1>;
			} ;
			dma-channel@40440030 {
				compatible = "xlnx,axi-dma-s2mm-channel";
				interrupts = <0 33 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x1>;
			} ;
		} ;
		axi_dma_2: axi-dma@40480000 {
			compatible = "xlnx,axi-dma";
			interrupt-parent = <&ps7_scugic_0>;
			interrupts = <0 33 4>, <0 34 4>;
			reg = <0x40480000 0x10000>;
			dma-channel@40480000 {
				compatible = "xlnx,axi-dma-mm2s-channel";
				interrupts = <0 32 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x2>;
			} ;
			dma-channel@40480030 {
				compatible = "xlnx,axi-dma-s2mm-channel";
				interrupts = <0 31 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x2>;
			} ;
		} ;
		axi_dma_3: axi-dma@404c0000 {
			compatible = "xlnx,axi-dma";
			interrupt-parent = <&ps7_scugic_0>;
			interrupts = <0 35 4>, <0 36 4>;
			reg = <0x404c0000 0x10000>;
			dma-channel@404c0000 {
				compatible = "xlnx,axi-dma-mm2s-channel";
				interrupts = <0 30 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x3>;
			} ;
			dma-channel@404c0030 {
				compatible = "xlnx,axi-dma-s2mm-channel";
				interrupts = <0 29 4>;
				xlnx,datawidth = <0x40>;
				xlnx,device-id = <0x3>;
			} ;
		} ;
	} ;

Notice how 28 and 30 are assigned to DMA 0. However, the mm2s channel has the interrupt at 36. Interrupt 29 is instead assigned to DMA 3's s2mm channel.

**Comment by nagasureshkumar** [comment]
Hi,
   The axi_dma.tcl logic has been updated, now there is now issue with interrupt
   IDs.

Thanks,
Naga Sureshkumar Relli.
