### ISSUE TITLE
There are no instructions ( README.md ) for this repo

### ISSUE THREAD

**Issue by thequbit** [Xilinx/device-tree-xlnx#4]
There is no way to know how to use this repo from github.

**Comment by ron2015schmitt** [comment]
it's xilinx, of course there are no instructions! ;)

read here: http://www.wiki.xilinx.com/Build+Device+Tree+Blob

**Comment by thequbit** [comment]
I'm aware that instructions exist else ware.  They should exist within this repo, and those instructions should be tied to a tag.

**Comment by ron2015schmitt** [comment]
I was trying to help you out.  Send your criticisms to xilinx.

**Comment by nagasureshkumar** [comment]
Hi,
Our Wiki page
http://www.wiki.xilinx.com/Build+Device+Tree+Blob
will tell How to use this repo.
